# Generated by Django 3.0.7 on 2020-07-10 12:26

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Youtube_Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtubeVideo', embed_video.fields.EmbedVideoField()),
                ('videoTitle', models.CharField(max_length=100)),
            ],
        ),
    ]
