# Generated by Django 3.0.7 on 2020-07-10 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_Stories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentUser', models.CharField(max_length=100)),
                ('commentContent', models.TextField()),
                ('commentDate', models.DateTimeField()),
                ('commentKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.Youtube_Entry')),
            ],
        ),
    ]
