# Generated by Django 3.0.7 on 2020-07-10 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_comment_stories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment_Stories',
            new_name='CommentStories',
        ),
    ]
