# Generated by Django 3.0.7 on 2020-07-10 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_youtube_entry_videourl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtube_entry',
            name='videoUrl',
        ),
    ]
