# Generated by Django 3.0.7 on 2020-07-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_remove_youtube_entry_videourl'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentstories',
            name='commentChannel',
            field=models.URLField(null=True),
        ),
    ]
