# Generated by Django 3.0.7 on 2020-07-11 15:32

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0008_commentstories_commentchannel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtube_entry',
            name='youtubeVideo',
            field=embed_video.fields.EmbedVideoField(unique=True),
        ),
    ]
